package:
  name: larray
  version: 0.29

source:
  git_tag: 0.29
  git_url: https://github.com/larray-project/larray.git
#  git_tag: master
#  git_url: file://c:/Users/gdm/devel/larray/.git

build:
  # If this is a new build for the same version, increment the build number
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  build:
    - pip
    - python

  run:
    - python
    - numpy >=1.10
    - pandas >=0.13.1

test:
#  requires:
#    - pytest
#    - pytables

  imports:
    - larray

#  commands:
#    # You can also put a file called run_test.py in the recipe that will be run at test time.
#    - pytest --pyargs larray

about:
  home: http://github.com/larray-project/larray
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: "Labeled N-dimensional array."
#  doc_url:
#  dev_url:

extra:
  recipe-maintainers:
    - alixdamman
    - gdementen

# See
# https://conda.io/docs/user-guide/tasks/build-packages/index.html
# for more information about meta.yaml
